### ISSUE TITLE
Error in installing ISLP on python 3.12.1

### ISSUE THREAD

**Issue by yasermehrali** [intro-stat-learning/ISLP#16]
Hello
I have error in installing ISLP on python 3.12.1
I have same error in virtual installing.

![image](https://github.com/intro-stat-learning/ISLP/assets/34983057/e26fafb3-1632-4ed4-b1ca-1d6981259fdd)

**Comment by jonathan-taylor** [comment]
Last I checked `torch` didn't even install on python3.12. Can you try python3.11?
