### ISSUE TITLE
Get details of ModelSpec blackbox

### ISSUE THREAD

**Issue by maelfosso** [intro-stat-learning/ISLP#26]
I am in the lab of chapter 2 and `ModelSpec` is a really important class. **Are we supposed to reuse this class in our work?**

I noticed that many things are hidden in the `ModelSpec`
Those things are important, according to me, for example
- Fit and Transformation
- Interaction Terms creation

How do you create the intercept from fit and transformation?
How do you create interaction terms from two features?

How can we know all those details?

**Comment by jonathan-taylor** [comment]
Documentation is [here](https://intro-stat-learning.github.io/ISLP/) (linked to on `statlearning.com` as well)
