### ISSUE TITLE
BART handling DataFrames incorrectly during prediction

### ISSUE THREAD

**Issue by allispaul** [intro-stat-learning/ISLP#9]
This throws an error:
```python
from ISLP import load_data
from ISLP.bart import BART

boston = load_data("Boston")
X, y = boston.drop('medv', axis=1), boston['medv']
bart_boston = BART(random_state=0, burnin=5, ndraw=15)
bart_boston.fit(X, y)
bart_boston.predict(X)
```
I'm pretty sure the issue is the line
```python
tree_fit = np.array([tree.predict_out_of_sample(x) for x in X])
```
from `BART.predict()`. If `X` is a NumPy array, iterating over it yields its rows, but if it's a Pandas DataFrame, iterating over it yields its column names.

I would be happy to send a PR for this if you all accept them!

**Comment by jonathan-taylor** [comment]
Apologies, just noticed this issue now. Yes, I think your logic is correct. Seems a simple `np.asarray(X)` would get much of what is needed done. Happy to look at a PR
